### PR TITLE
docs: Adds .github folder

### PR DESCRIPTION
**Pull request by grant**
# docs: Adds .github folder

- Creates a `.github` folder to keep the root directory clean.
- Moves the CONTRIBUTING.md file to a `.github` folder.
- Adds a standard `ISSUE_TEMPLATE.md`
- Adds a simple, single `PULL_REQUEST_TEMPLATE.md`

### CODE REVIEW

**Comment by rspier** [comment]
@willnorris What are your thoughts on this PR?  (I know you often have strong opinions about GitHub use.)

I think we need to leave the CONTRIBUTING.md in the top level, to keep it consistent with the long history of requiring it there.  I understand why you want to do it, but moving one file doesn't help much.  I'm also concerned about "out of sight, out of mind" with that file.  I might not notice that the file exists in the .github directory from a local checkout.  (i.e. it won't show up with `ls`)

Regarding the issue templates, I'm torn.  They're _slightly_ opinionated in a way that I'm not sure applies to all projects, and I'm not sure people will notice them to modify them.  An alternative would be to add them to the boilerplate README.md that people have to modify anyway.  On the other hand, they're harmless.

**Comment by willnorris** [comment]
issue and PR template totally make sense in the .github folder... they are not really useful outside the context of being used as a template, and are very GitHub specific.  Hiding them away is no problem.

I'm similarly torn on the contributing file, however.  Ideally, it *is* useful as a standalone file, so having it discoverable is helpful.  One interesting alternative, is that you can also place it in a "docs" folder, and GitHub will still find it.  I really like that in the sense that it encourages writing additional documentation.

Regardless of what we do in this repo, we should definitely update cross to accept putting the contributing file in all the places that GitHub supports.

**Comment by rspier** [comment]
> I'm similarly torn on the contributing file, however. Ideally, it _is_ useful as a standalone file, so having it discoverable is helpful. One interesting alternative, is that you can also place it in a "docs" folder, and GitHub will still find it. I really like that in the sense that it encourages writing additional documentation.

I'm concerned that the docs directory might not get noticed by someone.  It's hard to miss things at the top level.  We can't assume people are going to read the docs.

> issue and PR template totally make sense in the .github folder... they are not really useful outside the context of being used as a template, and are very GitHub specific. Hiding them away is no problem.

Since we all seem to agree about this, in order to move forward, do you want to remove the CONTRIBUTING.md move, and maybe add a note to the README.md that these files exist?  (It's not that a CONTRIBUTIMG.md move is off the table, but that I don't want to block everything on our ruminations.)

**Comment by willnorris** [comment]
> I'm concerned that the docs directory might not get noticed by someone. It's hard to miss things at the top level. We can't assume people are going to read the docs.

The whole point of us following GitHub's conventions is that they display them prominently in their UI.  For example, there used to be a butter bar whenever you open a new issue or PR.  It looks like that has moved to the sidebar, though it is made much more prominent on your first contribution to a given repo:

image

So honestly, I'm not that beholden to keeping the contributing file in the top-level directory.  If we *really* cared about making it prominent, we would enforce mentioning it in the README as well, but I don't think we really want to do that.

But if we *were* going to move the default location of the contributing file, we certainly couldn't do it before we updated cross to look in the new location.

**Comment by rspier** [comment]
I've filed an internal FR.  You're both CCed.

**Comment by grant** [comment]
I'm not able to make progress on this PR. I don't use this template repo since it doesn't provide a useful template that I can copy/paste.

As a result, I'll close this PR.

**Comment by willnorris** [comment]
reopening, since this is still a good change to make. We just need to update cross before we can merge this in.

**Comment by rspier** [comment]
The CL to cross landed two weeks ago.  Thanks @gauntface.  

I'd still like to leave the default location of CONTRIBUTING.md at the top level, but we could tell pepole that it's ok to move it into .github if they don't want it there?

**Comment by willnorris** [comment]
Talked with Robert, let's move the default contributing.md file into the docs directory.  First, we just need to make one more minor change to cross to allow lowercase "contributing.md".

**Comment by grant** [comment]
Let me know when you would like me to change the contents of this PR.

**Comment by willnorris** [comment]
you can go ahead and make the change now (just move contributing into a docs folder).  We'll just need to wait to merge it until we have the change in cross.  Thanks!

**Comment by grant** [comment]
- Renamed `contributing.md`
- Created new folder `docs`
- Moved `contributing.md` to `docs`

**Comment by willnorris** [comment]
okay, cl/267682432 is submitted.  It should autopush on Monday of next week, at which point we can merge this in.

**Comment by grant** [comment]
Will let you merge when ready.

**Comment by willnorris** [comment]
Verified that cross passes with these changes.

**Pull request merged**
